stages:
  - build
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Running API tests"
    - newman run C:/Users/Asus/Desktop/Postman/Collections/Collection.postman_collection.json --environment C:/Users/Asus/Desktop/Postman/Environments/Environment.postman_environment.json
    # Replace 'path/to/your/postman_collection.json' and 'path/to/your/postman_environment.json' with the actual paths to your Postman files

deploy:
  stage: deploy
  script:
    - echo "Deploying the API"


