build:
  stage: build
  script:
    - echo "Building the API"
    - apt-get update -qy  # Update the package lists (for Linux-based runners)
    - apt-get install -qy npm  # Install npm (for Linux-based runners)
    - npm ci  # Install project dependencies from package-lock.json or npm-shrinkwrap.json
